server:
  port: 8000
spring: 
  application:
    name: spring-cloud-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.0.99.68:3306/fznews_userinfo?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz@WSX 
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      filter:
        stat:
          enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:                                        # redis 配置
    host: localhost    #129.0.97.23 localhost
    port: 6379           #30453 6379 
#    cluster:
#      max-redirects: 6
#      nodes:
#      - 129.0.97.23:30453